### ISSUE TITLE
Unable to generate file without --flask argument

### ISSUE THREAD

**Issue by GollyJer** [ksindi/sqlacodegen#4]
Hi.  I was hunting for a version of sqlacodegen that would create backref references and your fork looked like it would do exactly that.  However, when I run the code without the --flask argument an empty file is created.  If I use --flask a full file is created but with much more than the backref additions.  I know this is alpha.  Just wondering if it's something you're still working on or not.

Thanks.

**Comment by ksindi** [comment]
Sorry for the late response. Thanks for letting me know. Should be fixed now.
