### ISSUE TITLE
Wrong code generated for timestamp, tinyint and boolean datatypes

### ISSUE THREAD

**Issue by hussaintamboli** [ksindi/sqlacodegen#5]
One of the table from my database is 

    create table sample (
    `id` INT NOT NULL AUTO_INCREMENT primary key,
    `country_id` tinyint NOT NULL,
    `modified_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `is_deleted` BOOLEAN NOT NULL DEFAULT '0')

The code generated by `sqlacodegen` is

    class Sample(db.Model):
        cache_label = u'default'
        cache_regions = regions
        query_class = query_callable(regions)

        __tablename__ = 'sample'

        id = db.Column(db.Integer, primary_key=True)
        country_id = db.Column(db.Integer, nullable=False)
        modified_on = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue())
        is_deleted = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue())

If I do vice versa, i.e. create a table (say sample2) using above code, I would get

    create table sample (
    `id` INT NOT NULL AUTO_INCREMENT primary key,
    `country_id` int NOT NULL,
    `modified_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `is_deleted` int NOT NULL DEFAULT '0')

As of now, I am manually changing the auto generated code.

**Comment by ksindi** [comment]
Unfortunately this issue is vendor (this this case MySQL) specific and out of the scope of this project. Not sure how to solve this without special case code.
